### PR TITLE
RU: upd

### PR DESCRIPTION
**Pull request by xteamlyer**
Add KPM Guide and info about ReZygisk by @RinLin-NYA #47

### CODE REVIEW

**Comment by AkinaAcct** [comment]
Wait what?

> info about ReZygisk by @RinLin-NYA https://github.com/AndroidPatch/APatchDocs/pull/47

**Comment by xteamlyer** [comment]
> Wait what?

This is not a draft and purely a small tip. Just thought I'd add a little something. If it's not necessary, I'll take it out.

**Comment by RinLin-NYA** [comment]
> Wait what?
> 
> > info about ReZygisk by @RinLin-NYA #47
> 
> @RinLin-NYA Is that finished?

It's just a draft resolution because it maybe cause some misunderstanding between APatch project and ZygiskNext developers(especially Nullptr), so that(

**Comment by RinLin-NYA** [comment]
We reverted this pr in commit d1d37ef, please remove the context about ReZygisk and pr again. Sorry for any unconvenience.

**Comment by xteamlyer** [comment]
> pr again.
#50

**Pull request merged**
